#!/usr/bin/env node
// Runs a pre-registered holdout experiment (data/pickem-backtest/experiment-2.json): models with
// values fixed in advance, walked through a decision chain on a season none of them was tuned
// on, then guarded against making this season worse. Writes
// data/pickem-backtest/{experiment}.results.md/.json. Local files only; no API calls.
//
// Usage: node scripts/holdout-pickem.mjs [--experiment experiment-2] [--draws 10000]

import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { PARAMS_V1 } from './lib/pickem-model-params.mjs';
import { evaluate } from './lib/pickem-backtest.mjs';
import { runChain } from './lib/pickem-holdout.mjs';
import { loadHistorySeason, loadSeasonWeeks, readJsonAt } from './lib/pickem-data.mjs';
import { teamWeekRows, meanBy, tier } from './lib/pickem-describe.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const args = process.argv.slice(2);
const opt = (name, dflt) => { const i = args.indexOf(name); return i === -1 ? dflt : args[i + 1]; };
const expId = opt('--experiment', 'experiment-2');
const spec = readJsonAt(ROOT, `data/pickem-backtest/${expId}.json`);
const OPTS = { draws: Number(opt('--draws', 10000)), seed: 20260923 };

const holdout = loadHistorySeason(ROOT, spec.data.holdout.season);
if (!holdout) {
  console.error(`data/pickem-history/${spec.data.holdout.season}-raw.json is missing -- fetch it with scripts/fetch-pickem-history.mjs first.`);
  process.exit(1);
}
const context = loadHistorySeason(ROOT, spec.data.context.season);
const check = loadSeasonWeeks(ROOT, spec.data.check.season);
const current = readJsonAt(ROOT, 'data/current.json');
const names = { ...holdout.names, ...(context?.names ?? {}), ...Object.fromEntries(Object.entries(current.teams).map(([id, t]) => [id, t.name])) };

const chainSpec = {
  models: Object.fromEntries(Object.entries(spec.models).map(([k, m]) => [k, m.params])),
  chain: spec.chain,
};
const result = runChain(holdout.records, check, chainSpec, OPTS);

const MODELS = { V1: PARAMS_V1, ...Object.fromEntries(Object.entries(chainSpec.models).map(([k, p]) => [k, { ...PARAMS_V1, ...p }])) };
if (!(result.final.name in MODELS)) MODELS[result.final.name] = result.final.params;

// ---- summaries -----------------------------------------------------------------------------------
function summarize(records) {
  const rows = teamWeekRows(records, MODELS);
  const stay = rows.filter((r) => !r.exited);
  const movers = stay.filter((r) => r.rootMover);
  const mean = (rs, f) => rs.reduce((s, r) => s + f(r), 0) / rs.length;
  const out = { 'no change': { wModel: evaluate(records, PARAMS_V1).wBase, skill: 0, mae: mean(stay, (r) => Math.abs(r.currentRank - r.actualRank)), rm: mean(movers, (r) => Math.abs(r.currentRank - r.actualRank)) } };
  for (const [name, params] of Object.entries(MODELS)) {
    const ev = evaluate(records, params);
    out[name] = {
      wModel: ev.wModel, skill: ev.skill,
      mae: mean(stay, (r) => Math.abs(r.proj[name] - r.actualRank)),
      rm: mean(movers, (r) => Math.abs(r.proj[name] - r.actualRank)),
    };
  }
  return { rows, n: stay.length, movers: movers.length, table: out };
}
const S = {
  holdout: summarize(holdout.records),
  check: summarize(check),
  context: context ? summarize(context.records) : null,
};

// ---- report --------------------------------------------------------------------------------------
const r2 = (x) => (x == null || !Number.isFinite(x) ? 'n/a' : String(Math.round(x * 100) / 100));
const pct = (x) => (x == null ? 'n/a' : `${Math.round(x * 1000) / 10}%`);
const signed = (x) => (x == null ? 'n/a' : `${x > 0 ? '+' : ''}${r2(x)}`);
const out = [];
const p = (s = '') => out.push(s);
const H = holdout.stats;

p(`# ${expId} results (generated by scripts/holdout-pickem.mjs)`);
p();
p(`Generated ${new Date().toISOString()} from \`data/pickem-backtest/${expId}.json\`. Bootstrap draws: ${OPTS.draws}, seed ${OPTS.seed}.`);
p();
p('## Data');
p();
p(`- **Holdout, ${spec.data.holdout.season}:** ${H.transitions} AP poll transitions, ${H.rankedTeamWeeks} ranked team-weeks, ${H.rankedGames} ranked games (${H.rankedFinal} final, ${H.rankedWithLine} with a line, ${H.rankedOpponentsWithElo} opponents with a pre-game Elo rank); two games in one CFBD week: ${H.doubleGames}. Fetched ${holdout.raw.fetchedAt}; CFBD calls ${holdout.raw.calls.length} (remaining before/after: ${holdout.raw.remainingCalls.before ?? '?'} / ${holdout.raw.remainingCalls.after ?? '?'}).`);
p(`- **Check, ${spec.data.check.season}:** ${check.map((c) => `week ${c.week} -> ${c.week + 1}`).join('; ')}.`);
p(`- **Context, ${spec.data.context.season}:** where the values were fit (not evidence).`);
p();
p('## Decision chain');
p();
p('| Step | Current -> candidate | Weighted errors (2024) | Gain | 5th pct | Weeks 1-8 / 9+ | Min gain without one team | Result |');
p('|---|---|---|---|---|---|---|---|');
for (const s of result.steps) {
  if (s.skipped) { p(`| ${s.step} | ${s.from} -> ${s.to} | | | | | | skipped (not on top of ${s.from}) |`); continue; }
  p(`| ${s.step} | ${s.from} -> ${s.to} | ${r2(s.eCurrent)} -> ${r2(s.eCandidate)} | ${signed(s.delta)} | ${signed(s.ci5)} | ${signed(s.early)} / ${signed(s.late)} | ${signed(s.minWithoutOneTeam)} (${names[s.worstTeam] ?? s.worstTeam}) | ${s.pass ? '**adopted**' : 'rejected'} |`);
}
p();
p(`2026 guard: V1 makes ${r2(result.guard.eV1)} weighted errors on 2026 weeks 1-3; ${result.guard.path.map((g) => `${g.name} ${r2(g.eCheck)}`).join(', ')}.${result.guard.steppedBack ? ' Stepped back.' : ''}`);
p();
p(`**Recommendation: ${result.final.name}** -- ${Object.entries(result.final.params).filter(([k, v]) => PARAMS_V1[k] !== v).map(([k, v]) => `${k}=${v}`).join(', ') || 'no change from V1'}.`);
p();
p('## Every model, every season');
p();
p('| Model | 2024 weighted errors (skill) | 2024 avg rank miss | 2024 root-mover miss | 2026 wk1-3 errors (skill) | 2026 avg miss | 2026 root-mover miss | 2025 errors (skill) |');
p('|---|---|---|---|---|---|---|---|');
for (const name of Object.keys(S.holdout.table)) {
  const h = S.holdout.table[name];
  const c = S.check.table[name];
  const x = S.context?.table[name];
  p(`| ${name} | ${r2(h.wModel)} (${pct(h.skill)}) | ${r2(h.mae)} | ${r2(h.rm)} | ${r2(c.wModel)} (${pct(c.skill)}) | ${r2(c.mae)} | ${r2(c.rm)} | ${x ? `${r2(x.wModel)} (${pct(x.skill)})` : 'n/a'} |`);
}
p();
p(`Average rank miss is over teams in both polls (2024: ${S.holdout.n}; 2026: ${S.check.n}); root movers 2024: ${S.holdout.movers}, 2026: ${S.check.movers}.`);
p();
p(`### ${spec.data.holdout.season} week by week (weighted pairwise errors)`);
p();
const modelNames = Object.keys(MODELS);
p(`| Poll wk | Weight | Real swaps | ${modelNames.join(' | ')} |`);
p(`|---|---|---|${modelNames.map(() => '---').join('|')}|`);
const evals = Object.fromEntries(modelNames.map((n) => [n, evaluate(holdout.records, MODELS[n]).weeks]));
holdout.records.forEach((rec, i) => {
  p(`| ${rec.week} | ${evals.V1[i].w} | ${evals.V1[i].dBase} | ${modelNames.map((n) => evals[n][i].dModel).join(' | ')} |`);
});
p();
p(`### ${spec.data.holdout.season} losses: real drop vs projected (exit = fell to #26)`);
p();
p(`| Loss | n | Real | ${modelNames.join(' | ')} | Exit rate |`);
p(`|---|---|---|${modelNames.map(() => '---').join('|')}|---|`);
const losses = S.holdout.rows.filter((r) => r.outcome === 'loss' || r.outcome === 'blowoutLoss');
const fields = { real: (r) => r.actualMove, ...Object.fromEntries(modelNames.map((n) => [n, (r) => r.projMove[n]])), exit: (r) => (r.exited ? 1 : 0) };
for (const g of meanBy(losses, (r) => `${r.oppRanked ? 'to ranked' : 'to unranked'}, was ${tier(r.currentRank)}`, fields)
  .sort((a, b) => a.key.localeCompare(b.key, undefined, { numeric: true }))) {
  p(`| ${g.key} | ${g.n} | ${signed(g.real)} | ${modelNames.map((n) => signed(g[n])).join(' | ')} | ${pct(g.exit)} |`);
}
p();
p(`### ${spec.data.check.season}: root movers and exits under each model`);
p();
p(`| Wk | Team | Result | vs line | Was | Real | ${modelNames.join(' | ')} |`);
p(`|---|---|---|---|---|---|${modelNames.map(() => '---').join('|')}|`);
for (const r of S.check.rows.filter((x) => x.rootMover || x.exited)) {
  const res = r.margin == null ? 'bye' : `${r.margin > 0 ? 'W' : 'L'} by ${Math.abs(r.margin)}`;
  p(`| ${r.week} | ${r.name} | ${res} | ${signed(r.surprise)} | ${r.currentRank} | ${r.actualRank ?? 'out'} | ${modelNames.map((n) => r.proj[n]).join(' | ')} |`);
}
p();

const report = out.join('\n');
writeFileSync(join(ROOT, `data/pickem-backtest/${expId}.results.md`), `${report}\n`);
writeFileSync(join(ROOT, `data/pickem-backtest/${expId}.results.json`), `${JSON.stringify({
  generatedAt: new Date().toISOString(), spec: expId, draws: OPTS.draws, seed: OPTS.seed, holdoutStats: H,
  steps: result.steps, guard: result.guard, recommendation: result.final,
  seasons: { holdout: S.holdout.table, check: S.check.table, context: S.context?.table ?? null },
}, null, 2)}\n`);
console.log(report);
console.log(`\nWrote data/pickem-backtest/${expId}.results.md and .results.json`);
